-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CANDIDATE_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'RECRUITER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PLATFORM_ADMIN';

-- AlterTable
ALTER TABLE "User" ADD COLUMN "mustChangePassword" BOOLEAN NOT NULL DEFAULT false;
