ALTER TYPE "BackgroundTaskType" RENAME VALUE 'RESUME_PARSE' TO 'RESUME_PARSING';
ALTER TYPE "BackgroundTaskType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_RETRY';

ALTER TYPE "BackgroundTaskStatus" RENAME VALUE 'COMPLETED' TO 'SUCCEEDED';
ALTER TYPE "BackgroundTaskStatus" RENAME VALUE 'RETRYING' TO 'RETRY_SCHEDULED';
ALTER TYPE "BackgroundTaskStatus" ADD VALUE IF NOT EXISTS 'DEAD_LETTER';
