ALTER TABLE "CandidateProfile"
ALTER COLUMN "currentCtcLpa" TYPE DOUBLE PRECISION USING "currentCtcLpa"::DOUBLE PRECISION,
ALTER COLUMN "expectedCtcLpa" TYPE DOUBLE PRECISION USING "expectedCtcLpa"::DOUBLE PRECISION;
