-- Walk-in job posting fields (additive, nullable / defaulted).
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "isWalkIn" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "walkInStartDate" TIMESTAMP(3);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "walkInEndDate" TIMESTAMP(3);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "walkInTiming" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "walkInContactName" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "walkInContactPhone" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "walkInVenueAddress" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "walkInGoogleMapsUrl" TEXT;
